;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        kill-region
        python-indent-dedent-line-backspace
        sgml-slash
        yas/expand
        ))

(setq mc/cmds-to-run-once
      '(
        kill-sentence
        scala-newline
        yank-rectangle
        ))
