;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ah:smart-start-of-line
        c-electric-brace
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        cljr-slash
        downcase-region
        electric-newline-and-maybe-indent
        end-of-buffer
        haskell-indentation-delete-char
        insert-parentheses
        iy-go-to-char
        iy-go-to-char--command
        kill-region
        org-beginning-of-line
        org-end-of-line
        org-return-indent
        org-self-insert-command
        paredit-backward-kill-word
        paredit-close-square
        paredit-doublequote
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-kill
        paredit-newline
        paredit-open-curly
        paredit-open-round
        paredit-open-square
        paredit-splice-sexp
        paredit-wrap-round
        python-indent-dedent-line-backspace
        python-indent-electric-colon
        sgml-slash
        smex
        sp--self-insert-command
        sp-forward-slurp-sexp
        upcase-region
        yas-expand
        yas/expand
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        kill-sentence
        scala-newline
        yank-rectangle
        ))
