;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        haskell-indentation-delete-char
        iy-go-to-char
        kill-region
        paredit-backward-kill-word
        paredit-doublequote
        paredit-forward-delete
        paredit-forward-slurp-sexp
        paredit-open-round
        paredit-splice-sexp
        python-indent-dedent-line-backspace
        python-indent-electric-colon
        sgml-slash
        smex
        yas/expand
        ))

(setq mc/cmds-to-run-once
      '(
        kill-sentence
        scala-newline
        yank-rectangle
        ))
